image: openjdk:11.0.3-jre-slim-stretch

stages:
  - build
  - test
  - pushImage

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew clean assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week


test:
  stage: test
  script:
    - bash ./gradlew check

pushImage:
  stage: test
  script:
    - bash ./gradlew pushImage
  only:
    - develop

#deploy:
#  stage: deploy
#  script:
#    - ./deploy

after_script:
  - echo "End CI"