version: '3.4'

services:
  ms-sublearn-translator:
    image: almazic91/sub-learn-translator:0.2.0
    ports:
      - 8080:8080
    environment:
        SPRING_PROFILES_ACTIVE: default
        SERVER_PORT: 8080
        YANDEX_DICT_URL:
        YANDEX_DICT_KEY:
        YANDEX_TRANSLATE_URL:
        YANDEX_TRANSLATE_KEY.:
